sudo: required

dist: xenial

# safelist
branches:
  only:
  - master
  - develop

language: python
python:
  - "3.7"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

stages:
  - name: test
    if: branch = master
  - name: develop
    if: branch = master AND type = pull_request
  - name: production
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      install: make travis-env
      services:
        - docker
      script:
        - make test
        - make code-style
      after_success:
        - codecov

    - stage: develop
      install: make travis-aws
      services:
        - docker
      script:
        - make ENV=latest aws-push-image

    - stage: production
      install: make travis-aws
      services:
        - docker
      script:
        - make ENV=prod aws-push-image
